apiVersion: v1
kind: ConfigMap
metadata:
  name: test-simple-chart-config
data:
  test: "value123"
  name: {{ .Values.name }}
  {{- with (index (lookup "v1" "Service" "kube-system" "traefik").status.loadBalancer.ingress 0) }}
  ip: {{ .ip }}
  {{- end }}
