apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nginx
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx
  # minReplicas is set to a value over 1, the Deployment default value, to validate that Fleet is able to take that
  # difference into account without marking the resulting bundle as `Modified` for as long as the actual replica count
  # is within the below range:
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 2
