apiVersion: v1
kind: Pod
metadata:
  name: "nginx-post-test-health"
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  restartPolicy: Never
  containers:
  - name: test
    image: registry.suse.com/bci/bci-base:15.7
    command:
    - /bin/sh
    - -c
    - |
      set -e
      echo "Testing nginx health..."
      
      curl -v nginx-service.default.svc.cluster.local:8080/missing-file 2>&1 | grep '200 OK'
      if [ $? -eq  0 ]; then
        echo "✓ Application reports healthy status"
        exit 0
      else
        echo "ERROR: Application is unhealthy!"
        exit 1
      fi
